apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: drupal-service
  name: drupal-service
spec:
  ports:
  - name: "30095"
    nodePort: 30095
    protocol: TCP
    port: 3095
  selector:
    app: drupal
  type: NodePort
status:
  loadBalancer: {}
